apiVersion: v1
kind: Service
metadata:
  name: backend-sv
  labels:
    name: backend-sv
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: backend
  type: ClusterIP